# Generated by Django 5.0.14 on 2026-05-27 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tracking_id', models.CharField(db_index=True, max_length=50)),
                ('webhook_type', models.CharField(choices=[('inbound_twa_app_status', 'inbound_twa_app_status'), ('inbound_twa_kyc_status', 'inbound_twa_kyc_status'), ('outbound_abc_app_status', 'outbound_abc_app_status'), ('outbound_abc_kyc_status', 'outbound_abc_kyc_status')], max_length=30)),
                ('direction', models.CharField(choices=[('inbound', 'inbound'), ('outbound', 'outbound')], max_length=10)),
                ('endpoint', models.CharField(max_length=500)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('source_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('ip_whitelisted', models.BooleanField(blank=True, null=True)),
                ('http_status', models.SmallIntegerField(blank=True, null=True)),
                ('success', models.BooleanField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.SmallIntegerField(default=0)),
                ('max_retries', models.SmallIntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='applications.student')),
            ],
            options={
                'db_table': 'webhook_logs',
                'indexes': [models.Index(fields=['next_retry_at'], name='webhook_log_next_re_d62ca5_idx')],
            },
        ),
    ]
