# Generated by Django 5.0.14 on 2026-07-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooklog',
            name='encrypted_payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
