# Generated by Django 5.0.14 on 2026-05-27 17:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('apaar_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F'), ('O', 'O')], max_length=1, null=True)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=200)),
                ('university_name', models.CharField(blank=True, max_length=200, null=True)),
                ('college_name', models.CharField(blank=True, max_length=200, null=True)),
                ('course_name', models.CharField(blank=True, max_length=200, null=True)),
                ('enrollment_number', models.CharField(blank=True, max_length=100, null=True)),
                ('admission_year', models.IntegerField(blank=True, null=True)),
                ('academic_session', models.CharField(blank=True, max_length=20, null=True)),
                ('academic_status', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('current_address', models.JSONField(blank=True, null=True)),
                ('permanent_address', models.JSONField(blank=True, null=True)),
                ('photo_path', models.CharField(blank=True, max_length=500, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=20, null=True)),
                ('otp_attempt_count', models.SmallIntegerField(default=0)),
                ('otp_locked', models.BooleanField(default=False)),
                ('application_status', models.CharField(choices=[('RECEIVED', 'RECEIVED'), ('PROCESSING', 'PROCESSING'), ('ISSUED', 'ISSUED'), ('REJECTED', 'REJECTED'), ('FAILED', 'FAILED')], default='RECEIVED', max_length=30)),
                ('kyc_status', models.CharField(choices=[('MIN_KYC', 'MIN_KYC'), ('FULL_KYC', 'FULL_KYC'), ('FAILED', 'FAILED'), ('REJECTED', 'REJECTED')], default='MIN_KYC', max_length=30)),
                ('m2p_entity_id', models.CharField(blank=True, max_length=100, null=True)),
                ('m2p_kit_no', models.CharField(blank=True, max_length=100, null=True)),
                ('m2p_token', models.TextField(blank=True, null=True)),
                ('twa_synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='ABCApiLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tracking_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('direction', models.CharField(choices=[('inbound', 'inbound'), ('outbound', 'outbound')], max_length=10)),
                ('endpoint', models.CharField(max_length=100)),
                ('http_method', models.CharField(max_length=10)),
                ('client_id', models.CharField(blank=True, max_length=100, null=True)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('http_status', models.SmallIntegerField(blank=True, null=True)),
                ('hmac_valid', models.BooleanField(blank=True, null=True)),
                ('success', models.BooleanField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('source_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abc_logs', to='applications.student')),
            ],
            options={
                'db_table': 'abc_api_logs',
            },
        ),
    ]
