# Generated by Django 5.0.14 on 2026-05-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='title',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
