# Generated by Django 5.0.14 on 2026-05-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_student_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pan_name_match_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pan_verified',
            field=models.BooleanField(default=False),
        ),
    ]
