# Generated by Django 5.0.14 on 2026-05-29 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_student_pan_name_match_score_student_pan_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='PANApiLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('apaar_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('endpoint', models.CharField(max_length=50)),
                ('request_url', models.CharField(max_length=500)),
                ('request_headers', models.JSONField(blank=True, null=True)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('http_status', models.SmallIntegerField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('success', models.BooleanField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('duration_ms', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pan_logs', to='applications.student')),
            ],
            options={
                'db_table': 'pan_api_logs',
            },
        ),
    ]
