# Generated by Django 5.0.14 on 2026-06-23 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_panapilog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='pan_name_match_score',
            new_name='aadhaar_name_match_score',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='pan_number',
            new_name='aadhaar_number',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='pan_verified',
            new_name='aadhaar_verified',
        ),
        migrations.AddField(
            model_name='student',
            name='aadhaar_ref_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='AadhaarApiLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('apaar_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('endpoint', models.CharField(max_length=50)),
                ('request_url', models.CharField(max_length=500)),
                ('request_headers', models.JSONField(blank=True, null=True)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('http_status', models.SmallIntegerField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('success', models.BooleanField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('duration_ms', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aadhaar_logs', to='applications.student')),
            ],
            options={
                'db_table': 'aadhaar_api_logs',
            },
        ),
        migrations.DeleteModel(
            name='PANApiLog',
        ),
    ]
