# Generated by Django 5.0.14 on 2026-07-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_rename_pan_name_match_score_student_aadhaar_name_match_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abcapilog',
            name='encrypted_request_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abcapilog',
            name='encrypted_response_payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
