# Generated by Django 5.0.14 on 2026-08-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_abcapilog_encrypted_request_payload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='consent_aadhaar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='consent_address_mismatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='consent_kyc_and_ppi',
            field=models.BooleanField(default=False),
        ),
    ]
