# Generated by Django 5.0.14 on 2026-08-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_student_consent_aadhaar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='consent_aadhaar',
            new_name='consent_aadhaar_ovd',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='consent_kyc_and_ppi',
            new_name='consent_ckycr',
        ),
        migrations.AddField(
            model_name='student',
            name='consent_kyc_ppi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='consent_terms_conditions',
            field=models.BooleanField(default=False),
        ),
    ]
