# Generated by Django 5.0.14 on 2026-08-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_rename_consent_aadhaar_student_consent_aadhaar_ovd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='kyc_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('MIN_KYC', 'MIN_KYC'), ('FULL_KYC', 'FULL_KYC'), ('FAILED', 'FAILED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=30),
        ),
    ]
