# Generated by Django 5.0.14 on 2026-05-27 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='M2PApiLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('apaar_id', models.CharField(db_index=True, max_length=50)),
                ('endpoint', models.CharField(max_length=50)),
                ('request_url', models.CharField(max_length=500)),
                ('request_headers', models.JSONField(blank=True, null=True)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('http_status', models.SmallIntegerField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('success', models.BooleanField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('duration_ms', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='m2p_logs', to='applications.student')),
            ],
            options={
                'db_table': 'm2p_api_logs',
                'indexes': [models.Index(fields=['student'], name='m2p_api_log_student_33988a_idx'), models.Index(fields=['apaar_id'], name='m2p_api_log_apaar_i_eb62d9_idx'), models.Index(fields=['endpoint', 'success'], name='m2p_api_log_endpoin_24cc4e_idx'), models.Index(fields=['-created_at'], name='m2p_api_log_created_5de383_idx')],
            },
        ),
    ]
