# Generated by Django 5.0.14 on 2026-06-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m2p', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='m2papilog',
            name='encrypted_request_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='m2papilog',
            name='encrypted_response_payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
