# Generated by Django 5.0.14 on 2026-05-27 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TWAApiLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('apaar_id', models.CharField(db_index=True, max_length=50)),
                ('tracking_id', models.CharField(db_index=True, max_length=50)),
                ('endpoint', models.CharField(max_length=50)),
                ('request_url', models.CharField(max_length=500)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('http_status', models.SmallIntegerField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('success', models.BooleanField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('duration_ms', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='twa_logs', to='applications.student')),
            ],
            options={
                'db_table': 'twa_api_logs',
            },
        ),
    ]
