"""
Django settings for tap_project project.

Generated by 'django-admin startproject' using Django 5.0.14.
"""

import os
from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env(
    DJANGO_DEBUG=(bool, False),
    DB_PORT=(int, 3306),
)

# Read .env file from one level above BASE_DIR and force overwrite existing keys
environ.Env.read_env(env_file=str(BASE_DIR.parent / '.env'), overwrite=True)

# Quick-start development settings - unsuitable for production
SECRET_KEY = env('DJANGO_SECRET_KEY')
DEBUG = env.bool('DJANGO_DEBUG', default=False)
ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',

    # Local apps
    'applications.apps.ApplicationsConfig',
    'cms.apps.CmsConfig',
    'm2p.apps.M2PConfig',
    'portal.apps.PortalConfig',
    'twa.apps.TwaConfig',
    'webhooks.apps.WebhooksConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tap_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tap_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD', default=''),
        'HOST': env('DB_HOST', default='localhost'),
        'PORT': str(env('DB_PORT', default=3306)),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ABC Integration Security Settings
ABC_CLIENT_ID = env('ABC_CLIENT_ID', default='')
ABC_CLIENT_SECRET = env('ABC_CLIENT_SECRET', default='')
ABC_STATUS_UPDATE_WEBHOOK_URL = env('ABC_STATUS_UPDATE_WEBHOOK_URL', default='')
ABC_KYC_STATUS_WEBHOOK_URL = env('ABC_KYC_STATUS_WEBHOOK_URL', default='')

# TWA Integration Security Settings
TWA_SYNC_URL = env('TWA_SYNC_URL', default='https://api.stage.transcorpint.com/user/external/onboard')
TWA_AUTH_TOKEN = env('TWA_AUTH_TOKEN', default='')
TWA_WEBHOOK_ALLOWED_IPS = env.list('TWA_WEBHOOK_ALLOWED_IPS', default=['127.0.0.1'])

# Media files configurations for photo storage
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Cashfree Verification & Aadhaar Security Settings
CASHFREE_BASE_URL = env('CASHFREE_BASE_URL', default='https://sandbox.cashfree.com/verification')
CASHFREE_CLIENT_ID = env('CASHFREE_CLIENT_ID', default=env('PAN_CLIENT_ID', default=''))
CASHFREE_CLIENT_SECRET = env('CASHFREE_CLIENT_SECRET', default=env('CASHFREE_SECRET_KEY', default=env('PAN_CLIENT_SECRET', default='')))

